eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8766

spring:
  application:
    name: cloud-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-server-ribbon #以api-a开头的请求都转发给eureka-server-ribbon
    api-b:
      path: /api-b/**
      serviceId: eureka-server-feign  #以api-b开头的请求都转发给eureka-server-ribbon




