eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-server-feign


server:
  port: 8765

feign.hystrix.enabled: true   #开启Feign自带的短路器
